### ISSUE TITLE
How to set the local?

### ISSUE THREAD

**Issue by dkrusenstrahle** [tkadauke/motion-i18n#1]
Hello,

How can I set a locale? There seems to be only a way to get the locale
but that isn´t very helpful.

Thanks!

**Comment by dgilperez** [comment]
Hey! 

Thanks for a beautiful simple gem. Can you ellaborate a bit on how to set the locale in the settings application? I'd like to add a wrapper for that to the gem as a PR, if you feel that's interesting.

Thanks!

**Comment by YogeshMongar** [comment]
hi,
I added the following in the rake file
I18n.locale = 'de' and i am able to change it there. But in my app delegate the locale is back to 'en'.
Even tried with default locale but it somehow reverts back to 'en'. Why is the change not persisting?

**Comment by tkadauke** [comment]
The locale is set in system settings on your iPhone/iPad or in the simulator. Setting it in the Makefile or in the app has no effect.

**Comment by augustosamame** [comment]
Hi. I'm putting this on the Readme since I spent about an hour trying to set the locale and kept getting the following error:

undefined method `locale=' for I18n:Class (NoMethodError)

until I stumbled upon this closed issue.
I agree it does make sense to set the locale in the device or simulator settings, but as it differs from setting the locale for the I18n gem, it should be documented.

**Comment by tkadauke** [comment]
Absolutely, feel free to send a pull request! :)

**Comment by augustosamame** [comment]
Done! Thanks for the great gem!
